export type AudioSourceMode = 'rd_priority' | 'youtube_only';

export interface AppSettings {
  language: 'en' | 'it';
  homeDisplayOptions: {
    showRecentlyPlayed: boolean;
    showPlaylists: boolean;
    showNewReleases: boolean;
    showPopularArtists: boolean;
    showTopCharts: boolean;
  };
  audioQuality: 'high' | 'medium' | 'low';
  crossfade: number; // seconds, 0 = off
  realDebridApiKey?: string;
  audioSourceMode: AudioSourceMode; // 'rd_priority' = RD + YouTube fallback, 'youtube_only' = YouTube only
}

export const defaultSettings: AppSettings = {
  language: 'en',
  homeDisplayOptions: {
    showRecentlyPlayed: true,
    showPlaylists: true,
    showNewReleases: true,
    showPopularArtists: true,
    showTopCharts: true,
  },
  audioQuality: 'high',
  crossfade: 0,
  realDebridApiKey: undefined,
  audioSourceMode: 'rd_priority',
};

export const translations = {
  en: {
    home: 'Home',
    search: 'Search',
    library: 'Library',
    settings: 'Settings',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    whatToListen: 'What do you want to listen to?',
    recentlyPlayed: 'Recently Played',
    yourPlaylists: 'Your Playlists',
    newReleases: 'New Releases',
    popularArtists: 'Popular Artists',
    topCharts: 'Top Charts',
    searchPlaceholder: 'What do you want to listen to?',
    noResults: 'No results for',
    exploreByGenre: 'Explore by genre',
    artists: 'Artists',
    albums: 'Albums',
    tracks: 'Tracks',
    popular: 'Popular',
    discography: 'Discography',
    account: 'Account',
    realDebrid: 'Real-Debrid',
    playback: 'Playback',
    display: 'Display',
    audioQuality: 'Audio Quality',
    crossfade: 'Crossfade',
    language: 'Language',
    homeDisplay: 'Home Display',
    logout: 'Logout',
    login: 'Login',
    email: 'Email',
    password: 'Password',
    apiKey: 'API Key',
    connected: 'Connected',
    high: 'High (320 kbps)',
    medium: 'Medium (160 kbps)',
    low: 'Low (96 kbps)',
    off: 'Off',
    seconds: 'seconds',
    bugs: 'Bugs',
    alternativeSources: 'Alternative Sources',
    selectSource: 'Select a different source',
    noAlternatives: 'No alternative sources found',
    createPlaylist: 'Create Playlist',
    addYourFavorites: 'Add your favorite songs',
    likedSongs: 'Liked Songs',
    playlist: 'Playlist',
    artist: 'Artist',
    album: 'Album',
    cloudFiles: 'Cloud Files',
    noCloudFiles: 'No files saved on Real-Debrid yet',
    loadingCloudFiles: 'Loading cloud files...',
    playFromCloud: 'Play from cloud',
    audioSource: 'Audio Source',
    rdPriority: 'Real-Debrid + YouTube',
    rdPriorityDesc: 'High quality (FLAC/320kbps), YouTube fallback',
    youtubeOnly: 'YouTube Only',
    youtubeOnlyDesc: 'Instant playback, no Real-Debrid needed',
  },
  it: {
    home: 'Home',
    search: 'Cerca',
    library: 'Libreria',
    settings: 'Impostazioni',
    goodMorning: 'Buongiorno',
    goodAfternoon: 'Buon pomeriggio',
    goodEvening: 'Buonasera',
    whatToListen: 'Cosa vuoi ascoltare oggi?',
    recentlyPlayed: 'Ascoltate di recente',
    yourPlaylists: 'Le tue playlist',
    newReleases: 'Nuove uscite',
    popularArtists: 'Artisti popolari',
    topCharts: 'Classifiche',
    searchPlaceholder: 'Cosa vuoi ascoltare?',
    noResults: 'Nessun risultato per',
    exploreByGenre: 'Esplora per genere',
    artists: 'Artisti',
    albums: 'Album',
    tracks: 'Brani',
    popular: 'Popolari',
    discography: 'Discografia',
    account: 'Account',
    realDebrid: 'Real-Debrid',
    playback: 'Riproduzione',
    display: 'Display',
    audioQuality: 'Qualità audio',
    crossfade: 'Crossfade',
    language: 'Lingua',
    homeDisplay: 'Display Home',
    logout: 'Esci',
    login: 'Accedi',
    email: 'Email',
    password: 'Password',
    apiKey: 'API Key',
    connected: 'Connesso',
    high: 'Alta (320 kbps)',
    medium: 'Media (160 kbps)',
    low: 'Bassa (96 kbps)',
    off: 'Off',
    seconds: 'secondi',
    bugs: 'Bugs',
    alternativeSources: 'Fonti alternative',
    selectSource: 'Seleziona una fonte diversa',
    noAlternatives: 'Nessuna fonte alternativa trovata',
    createPlaylist: 'Crea playlist',
    addYourFavorites: 'Aggiungi i tuoi brani preferiti',
    likedSongs: 'Brani piaciuti',
    playlist: 'Playlist',
    artist: 'Artista',
    album: 'Album',
    cloudFiles: 'File Cloud',
    noCloudFiles: 'Nessun file salvato su Real-Debrid',
    loadingCloudFiles: 'Caricamento file cloud...',
    playFromCloud: 'Riproduci da cloud',
    audioSource: 'Sorgente Audio',
    rdPriority: 'Real-Debrid + YouTube',
    rdPriorityDesc: 'Alta qualità (FLAC/320kbps), fallback YouTube',
    youtubeOnly: 'Solo YouTube',
    youtubeOnlyDesc: 'Riproduzione istantanea, senza Real-Debrid',
  },
};

export type TranslationKey = keyof typeof translations.en;
